language: elixir
elixir:
  - 1.0.5
  - 1.1.1
otp_release:
  - 17.4
matrix:
  include:
    - elixir: 1.2.6
      otp_release: 18.1
    - elixir: 1.2.6
      otp_release: 18.2
    - elixir: 1.2.6
      otp_release: 18.3
    - elixir: 1.4.0
      otp_release: 18.3
      
sudo: false
  
env: MIX_ENV=test
